server:
  port: 8001
  tomcat:
    uri-encoding: UTF-8
spring:
  cache:
    ehcache:
      config: classpath:/ehcache/ehcache.xml
    type: ehcache
  redis:
#    host: db-replication.redis.svc.flybycs.com
    host: localhost
    password: feibaredis
    port: 6379
    timeout: 5000ms
    database: 2
    lettuce:
      pool:
        max-active: 10
        max-wait: -1
        max-idle: 10
        min-idle: 1
  datasource:
    # 使用druid数据源
    druid:
      url: jdbc:mysql://other-mysql-flyby-100.mysql.svc.flybycs.com/flybycloud?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
      username: chenyoujing
      password: D6iJZ11pxcrMexykBg
      driver-class-name: com.mysql.cj.jdbc.Driver
      filters: stat
      maxActive: 300
      initialSize: 5
      maxWait: 60000
      minIdle: 5
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdl eTimeMillis: 300000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
ibeplus:
  #ota：生产环境，目前阶段不要提交  develop：测试环境
  baseurl: http://espeed.srv.prod.flybytrip.com/develop/
  ota:
    username: hzxs
    password: 95Zy95Zqn4Rg  #测试环境密码
    #password: Gx58aT2p03iP   #生成环境密码
    iatanumber: 08315860


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true


xxl:
  job:
    admin:
      addresses: http://flyby-task-admin.develop.svc.flybycs.com/
    accessToken:
    executor:
      appname: flight-cache-run
      logretentiondays: 30
      logpath: ./logs