server:
  port: 8001
  tomcat:
    uri-encoding: UTF-8
spring:
  cache:
    ehcache:
      config: classpath:/ehcache/ehcache.xml
    type: ehcache
  redis:
    host: db-replication.redis.svc.flybycs.com
    password: feibaredis
    port: 6379
    timeout: 5000ms
    database: 2
    lettuce:
      pool:
        max-active: 10
        max-wait: -1
        max-idle: 10
        min-idle: 1
ibeplus:
  #ota：生产环境，目前阶段不要提交  develop：测试环境
  baseurl: http://espeed.srv.prod.flybytrip.com/develop/
  ota:
    username: hzxs
    password: 95Zy95Zqn4Rg  #测试环境密码
    #password: Gx58aT2p03iP   #生成环境密码
    iatanumber: 08315860



xxl:
  job:
    admin:
      addresses: http://flyby-task-admin.develop.svc.flybycs.com/
    accessToken:
    executor:
      appname: flight-cache-run
      logretentiondays: 30
      logpath: ./logs